### ISSUE TITLE
Associate CSS & JS in a dedicated folder

### ISSUE THREAD

**Issue by bcalou** [teddyboirin/greeny#11]
Bonne pratique courante : chaque couple JS/CSS a son dossier.
Dans un dossier, il n'y a que deux fichiers : le js et le css d'un composant précis

**Comment by edenbergel** [comment]
et si il y a un fichier scss commun à plusieurs fichiers js

**Comment by bcalou** [comment]
Tu peux préciser ton exemple ? Merci

**Comment by bcalou** [comment]
De manière générale dans ce cas on met le fichier scss plus haut dans l'arborescence. Les fichiers globaux peuvent avoir leur propre dossier.

**Comment by edenbergel** [comment]
par exemple dans ma page compte (dossier account), j'ai le fichier global account.js et trois autre fichier (composant: category.js, infoperso.js, reccurent.js). Tous partage le même fichier scss.

Sinon je met un fichier scss pour chaque "sous-composant" plutôt que d'avoir un fichier scss du composant global

**Comment by bcalou** [comment]
Oui, la deuxième solution ;)
C'est plus modulaire. Chaque composant a son css

**Comment by edenbergel** [comment]
ok je vais faire ça merci !
