### ISSUE TITLE
Use SASS loops

### ISSUE THREAD

**Issue by bcalou** [teddyboirin/greeny#8]
Dans account.scss et category.scss, l'usage d'une boucle SASS s'impose !
Quand vous itérez sur nth-child.

https://sass-lang.com/documentation/at-rules/control/each

**Comment by edenbergel** [comment]
J'ai un souci pour cibler les nth je sais pas si c'est la bonne façon de faire 

$bgColors: $lightPink, $lightYellow, $lightGreen, $lightBlue, $lightRed, $lightOrange;
$nth: 1, 2, 3, 4, 5, 6;

@each $bgColor in $bgColors {
    .defis_categ_bloc:nth-of-type(#{$nth}) div {
      background-color: $bgColor;
    }
  }

**Comment by bcalou** [comment]
En effet avec SASS ce n'est pas évident la première fois.

Tu peux faire ainsi :

```
$bgColors: $lightPink, $lightYellow, $lightGreen, $lightBlue, $lightRed, $lightOrange;

@each $bgColor in $bgColors {
.defis_categ_bloc:nth-of-type(#{index($bgColors, $bgColor)}) div {
background-color: $bgColor;
}
}
```

La fonction index permet de récupérer 1, 2, 3...

Pas d'inquiétude si ce n'est pas implémenté demain nous verrons ensemble. J'espère ne pas avoir fait d'erreur, essaie mon example !

Voir ici :  https://stackoverflow.com/a/24243797

**Comment by edenbergel** [comment]
Super merci ça marche :)
