### ISSUE TITLE
Uniformiser les messages de commit

### ISSUE THREAD

**Issue by bcalou** [teddyboirin/greeny#9]
À partir de maintenant, merci d'utiliser une convention de nommage pour vos commits. En voici une courante :

- En anglais
- Phrase à l'impératif
- Commence par un ou plusieurs mots clés

Exemples : 

```
[sass] add header styles
[js] add title to home components 
```

Je fermerai cette issue moi même la prochaine fois en vérifiant que la convention est bien suivie !

**Comment by edenbergel** [comment]
À chaque fois qu'on push il faut séparer nos commit scss et js ?

**Comment by bcalou** [comment]
Non, vous pouvez soit combiner les tags [sass][js] ou utiliser un tag global [tpl] quand vous touchez à tout (tpl pour template)

**Comment by bcalou** [comment]
C'est mieux !
